### ISSUE TITLE
train on multiple gpus

### ISSUE THREAD

**Issue by ethanyhzhang** [louis-she/sfd.pytorch#30]
can the code trained on multiple gpus? 
when training on a single gpu, it just fine.
while training on multiple ones, errors like as below happen
"RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_153│|  No running processes found                                                 |
3672544752/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:314"

thanks~

**Comment by louis-she** [comment]
Multiple GPU is supported
