### ISSUE TITLE
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:314

### ISSUE THREAD

**Issue by lilmangolil** [louis-she/sfd.pytorch#31]
I want to know how to deal with this kind of error.Thank you very much!
the error is:
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:314

**Comment by louis-she** [comment]
Did you modify the `device` option in `config.py` ?
