### ISSUE TITLE
about anchor

### ISSUE THREAD

**Issue by foralliance** [louis-she/sfd.pytorch#32]
@louis-she  HI

感觉anchor的设置有点问题．感觉您是完全按照paper中的fig1(3)设置的．
比如：
image的size为640．
在5*5的特征图上，anchor尺度为512，stride为128．根据您的代码，第1个anchor的坐标形式为(256,256,512,512)．中心点的位置很奇怪．难道不应该是(64,64,512,512)这样的anchor吗？？

**Comment by louis-she** [comment]
@foralliance 非常感谢指正，已经修复 https://github.com/louis-she/sfd.pytorch/commit/61b3be4eb7d7ef02413395424fa0a1f280086fd0
