### ISSUE TITLE
about tiny face

### ISSUE THREAD

**Issue by foralliance** [louis-she/sfd.pytorch#33]
@louis-she  HI
根据**caffe源码**的[#7](https://github.com/sfzhang15/SFD/issues/7)，因为eval_tools的原因，需要屏蔽掉tiny faces．原作者指出：When training，we do not use these extremely tiny faces (i.g., width or height＜6 pixels).
但在您的代码中，并未体现这一点！！

谢谢！

**Comment by louis-she** [comment]
Hi @foralliance  
这个repo复现了一下S3FD，wider face只是用来训练的，我并没有仔细看wider face的文档。
另外你可以自行修改evaluation_metrics.py里面计算 AP 的代码
